# Generated by Django 2.2.19 on 2021-05-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(default='', max_length=30)),
                ('contact', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=100)),
                ('disc', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=30)),
                ('tags', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
