# Generated by Django 2.2.19 on 2021-04-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('tags', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
