# Generated by Django 2.2.19 on 2021-04-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='date',
        ),
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='contact',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='discription',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='info',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='info',
            name='tags',
            field=models.CharField(default='', max_length=20),
        ),
    ]
