# Generated by Django 2.2.19 on 2021-04-29 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_auto_20210429_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='discription',
            new_name='disc',
        ),
    ]
