# Generated by Django 2.2.19 on 2021-04-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_auto_20210429_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(default='', max_length=30)),
                ('contact', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
